.TH ate 7 2023-07-04 "" "Miscellaneous Information Manual"
\" Set flag to remove TH header in included .so files:
.nr include_flag 1

.so ate7/macros.7
.so ate7/name.7
.so ate7/synopsis.7
.so ate7/description.7
.so ate7/basics.7
.so ate7/declare.7
.so ate7/table_info.7 \" get_row_size, get_row_count, get_array_name, get_field_sizes
.so ate7/get_put_row.7

