.TH ate 7 2023-07-04 "" "Miscellaneous Information Manual"
\" Set flag to remove TH header in included .so files:
.nr include_flag 1

.so ate.7.d/macros.7
.so ate.7.d/name.7
.so ate.7.d/synopsis.7

.so ate.7.d/description.7
.so ate.7.d/making_tables.7
.so ate.7.d/table_info.7


.so ate.7.d/error_handling.7

.ig OLD_CONTENT
.so ate.7.d/old/description.7
.so ate.7.d/old/basics.7
.so ate.7.d/old/declare.7
.so ate.7.d/old/table_info.7 \" get_row_size, get_row_count, get_array_name, get_field_sizes
.so ate.7.d/old/get_put_row.7
.so ate.7.d/old/resize_rows.7
.so ate.7.d/old/reindex_elements.7
.so ate.7.d/old/walk_rows.7
.so ate.7.d/old/sort.7
.OLD_CONTENT
