.if \n[include_flag]==0 \{\
.  TH debug 1
.  so macros.7
.\}
.SH DESCRIPTION
While
.B ate
is not very complicated, it usually requires multiple steps and calls to
.B ate
to do useful work with the command.
Examples of involved solutions should help developers to become
productive with
.B ate
more quickly.
