.if \n[include_flag]==0 \{\
.  TH debug 1
.  so macros.1
.\}
.SH DESCRIPTION
.PP
Standard Bash arrays are one-dimensional and sequential (slow) access.
.B ate
manages an index to virtual row heads for a two-dimensional aspect
with fast random access.
.PP
Implemented as a builtin, it uses Bash primitive variables, it can
call Bash script functions, and it runs in the same process as the
shell script for improved performance.

