.\" -*- mode: nroff -*-
.so fork.tmac
.SH ENABLING ATE
.EE
The
.B ate
loadable builtin must be enabled before its features can be used.
The
.B enable
command must be included in any script that wants to use
.BR ate ,
or it can be included in the
.B .bashrc
file for universal access.
.PP
Use the
.B enable
command to prepare
.B ate
for use:
.IP
.EX
enable -f /path/to/ate ate
.EE
.PP
.PP
If
.B ate
has been installed using
.BR "sudo make install" ,
there will be a script that makes enabling
.B ate
much easier.
Put the following statement in your script or your
.B .bashrc
file.
.IP
.EX
enable ate
.EE
.SS ate_sources
.PP
While installing the
.B ate
package, multiple
.B ate
utilities were also installed.  Enable the utilities with the
.B ate_sources
command.
.PP
Calling
.B ate_sources
without any arguments will list the available
.B ate
utilities.
Include a utility in a project by invoking
.B ate_sources
with the name of the utility:
.PP
.EX
.BR ate_sources " ate_exit_on_error"
.EE
