.if \n[include_flag]==0 \{\
.  TH debug 1
.  so macros.1
.\}
.SH ENABLING ATE
.EE
The
.B ate
loadable builtin must be enabled before its features can be used.
The
.B enable
command must be included in any script that wants to use
.BR ate ,
or it can be included in the
.B .bashrc
file for universal access.
.PP
Use the
.B enable
command to prepare
.B ate
for use:
.IP
.EX
enable -f /path/to/ate.so ate
.EE
.PP
.PP
If
.B ate
has been installed using
.BR "sudo make install" ,
there will be a script that makes enabling
.B ate
much easier.
Put the following statement in your script or your
.B .bashrc
file.
.IP
.EX
enable $( enable_ate )
.EE
