.if \n[include_flag]==0 \{\
.  TH debug 1
.  so macros.1
.\}
.SH RETURN VALUES
.PP
The
.B ate
command returns an exit status that indicates the result of the
call.
Following Linux custom, an exit status of zero
.RI ( 0 )
indicates success and will be interpreted as
.B true
by Bash in
.BR if " and " while
statements.
.PP
Errors are indicated by non-zero exit status, with the exception of the
.B seek_key
action that differentiates between an exact or approximate match as
well as an error condition.
.PP
When the exit status is not zero, the
.B ATE_ERROR
variable will contain an explanation of the error.
.SS SPECIAL RESULT VARIABLES
.PP
Certain actions produce results that must be examined.
.BR ATE_VALUE " and " ATE_ARRAY
are the default result variable names for simple values and array
values, respectively.
Actions
.BR get_row_count ", " get_row_size ", " get_array_name ", " seek_key
each report simple results and
.BR get_field_sizes " and " get_row
report array results.
.PP
The default result variable can be changed by naming an alternative
variable name using
.B -v
for simple simple values and
.B -a
for array values.
