.if \n[include_flag]==0 \{\
.  TH debug 1
.  so macros.1
.\}
.SH SYNOPSIS
.PP
.B ate
.I action_name handle_name
.RB [ "-a " "\fIarray_name\fP" ]
.RB [ "-v " "\fIvalue_name\fP" ]
.RI [ "extra ..." ]
.TP
.proto_list_actions
Show list of action names
.TP
.proto_show_action
Show details about
.IR action_name .
.PP
.proto_declare
.PP
.proto_append_data
.PP
.proto_index_rows
.PP
.proto_get_row_count
.PP
.proto_get_row_size
.PP
.proto_get_array_name
.PP
.proto_get_field_sizes
.PP
.proto_get_row
.PP
.proto_put_row
.PP
.proto_resize_rows
.PP
.proto_reindex_elements
.PP
.proto_walk_rows
.PP
.proto_sort
.PP
.proto_filter
.PP
.proto_make_key
.PP
.proto_seek_key

