.if \n[include_flag]==0 \{\
.  TH debug 1
.  so macros.1
.\}
.\" chanageable intra-prototype spacing:
.de  syn_int
.  br
..
.SH SYNOPSIS
.PP
.B ate
.print_prototype @action_name @handle_name ?-a:array_name ?-v:value_name "?@extra ..."
.PP
.B enable ate
.br
.BR source " <( ate_sources ate_exit_on_error ate_noop )"
.SS Usage help actions
.proto_list_actions
.syn_int
.proto_show_action
.SS Table manipulation actions
.syn_int
.proto_declare
.syn_int
.proto_append_data
.syn_int
.proto_index_rows
.syn_int
.proto_get_row_count
.syn_int
.proto_get_row_size
.syn_int
.proto_get_array_name
.syn_int
.proto_get_field_sizes
.syn_int
.proto_get_row
.syn_int
.proto_put_row
.syn_int
.proto_resize_rows
.syn_int
.proto_reindex_elements
.syn_int
.proto_seek_key
.SS Actions invoking callback functions
.syn_int
.proto_walk_rows
.syn_int
.proto_sort
.syn_int
.proto_filter
.syn_int
.proto_make_key
.SS Callback functions
.syn_int
.proto_walk_rows_callback
.syn_int
.proto_sort_callback
.syn_int
.proto_filter_callback
.syn_int
.proto_make_key_callback
