.if \n[include_flag]==0 \{\
.  TH debug 1
.  so macros.1
.\}
.SH SYNTAX
.PP
General command syntax follows Unix Utility conventions.
Action-specific syntax is show as command prototypes in the
.B SYNOPSIS
section above and in each action description below.
.TP
.B Command arguments
are all the strings that follow the
.B ate
command and consist of
.BR operands ", " options ", and " "option arguments" .
.TP
.B Operands
are undecorated strings that are read in order, the first
of which must be the.
.IR action_name .
.TP
.BR Options " and " "option arguments"
letters with a hyphen prefix,
can follow the
.I action_name
in any order, before, after, or between any operands.
.IP
Options without arguments can be grouped into a single string,
.IR "-ir" " is the same as " "-i -r" .
.IP
If an option takes an argument, the option letter must be the last
letter before the option argument, especially if the options are
grouped.
.IP
The space between an option and its argument is optional.
That means that
.BI "-s " starting_index
is the same as
.BI -s starting_index \c
\&.
