#!/usr/bin/env bash

enable -f ./ate.so ate

declare OIFS="$IFS"

declare -a test_array=(
    bob smith stockbroker
    katy jones CEO
    gertrude johansen sauna\ salesperson
    tommy ride used\ car\ salesman
    jacob smaby general\ contractor
)

if ate declare handle test_array 3; then
    echo "The handle was created."
    if ate get_row_count handle; then
        echo "There are $ATE_VALUE rows"
        if ate get_row handle 3 newrow; then
            echo "Got a row, its contents are:"
            IFS=$'\n'
            echo "${newrow[*]}"
            IFS="$OIFS"

            echo "About to change the profession to 'hobo'"
            newrow[2]="hobo"
            if ate put_row handle 3 newrow; then
                echo "It seems to have succeeded."
            else
                echo "It seems to have FAILED."
            fi
        else
            echo "Failed to get the row."
        fi
    fi
else
    echo "Failed to declare the handle"
fi

IFS=$'\n'
echo "${test_array[*]}"
