.if \n[include_flag]==0 \{\
.  TH debug 1
.  so macros.7
.\}
.SH DESCRIPTION
.PP
This document demonstrates how to use the
.B ate
command through discussion and examples.
.PP
Refer to the
.B ERROR HANDLING
section below to see a discussion of the
.B exit_on_error
function that is used throughout this tutorial to respond to errors.
