.if \n[include_flag]==0 \{\
.  TH debug 1
.  so macros.7
.\}
.SH DECLARING ATE TABLES
.PP
Bash arrays are the heart of
.B ate
tables.
.SS DEMO DATA
.PP
For many examples in this tutorial, we will be starting with the data
in the following array describing a three-column table:
.IP
.EX
declare -a pets_array=(
    Nemo    fish    2010-06-06
    Spot    dog     2014-08-06
    Fluffy  cat     2015-07-21
    Polly   parrot  1978-01-17
)
.EE
.SS TABLE-MAKING OPTIONS
There are two ways to make an
.B ate
table from the data, embedding the array in the
.B ate
handle, or by making an empty table and adding the data through the
.BR append_data " and " index_rows
actions.
.TP
.B Embedded array method:
.EX
ate declare pet_table 3 pets_array
exit_on_error
.EE
.TP
.B Fill empty table method using append_data:
.EX
ate declare pet_table 3
exit_on_error

ate append_data pet_table \(dq\(Do{pets_array[@]}\(dq
exit_on_error

ate index_rows pet_table
exit_on_error
.EE
.TP
.B Fill empty table method using get_array_name:
.EX
ate declare pet_table 3
exit_on_error

ate get_array_name pet_table -v array_name
exit_on_error

declare -n array_ref=\(dq\(Doarray_name\(dq
array_ref+=( \(dq\(Dopets_array[@]}\(dq )

ate index_rows pet_table
exit_on_error
.EE
.SS MISSING VALUES
.PP
Data imported into
.B ate
tables must have values for every field.
Failing to provide a field value in a row will result in a
misaligned table.
.PP
Using the pet array to track vaccinations, one might want to create
a four-column table with an empty field to be filled dates of
vaccinations after they are given.
.IP
.EX
declare -a pets_array=(
    Nemo    fish    2010-06-06
    Spot    dog     2014-08-06
    Fluffy  cat     2015-07-21
    Polly   parrot  1978-01-17
)

ate declare pet_table 4 pets_array
exit_on_error

print_formatted_table pet_table
.EE
.PP
The 12 elements of the
.I pets_array
array will be distributed to 3 rows of 4, resulting in a
misaliged table that looks like this:
.IP
.EX
Nemo       fish       2010-06-06 Spot
dog        2014-08-06 Fluffy     cat
2015-07-21 Polly      parrot     1978-01-17
.EE
